//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityData
{
    using System;
    using System.Collections.Generic;
    
    public partial class TEST_Customer
    {
        public Nullable<System.DateTime> Month { get; set; }
        public string EndUser { get; set; }
        public Nullable<double> AverageStock { get; set; }
        public Nullable<double> TurnoverRate { get; set; }
        public Nullable<double> NumOfOverdue { get; set; }
        public Nullable<double> SlowSalesRate { get; set; }
        public Nullable<double> ReturnRate { get; set; }
        public Nullable<double> BreakageRate { get; set; }
        public Nullable<double> MonCumlShipQty { get; set; }
        public Nullable<double> UnitPrice { get; set; }
        public Nullable<decimal> MonCumlShipAmt { get; set; }
        public string F12 { get; set; }
        public string CreditRating { get; set; }
        public Nullable<double> CreditScore { get; set; }
        public string CanRaiseCapital { get; set; }
        public Nullable<decimal> CapitalAmt { get; set; }
        public string CapitalExpense { get; set; }
        public int ID { get; set; }
    }
}
